/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OurTeamImport } from './routes/our-team'
import { Route as OurOfficesImport } from './routes/our-offices'
import { Route as ContactImport } from './routes/contact'
import { Route as ComingSoonImport } from './routes/coming-soon'
import { Route as AuthImport } from './routes/auth'
import { Route as AboutUsImport } from './routes/about-us'
import { Route as AboutMeImport } from './routes/about-me'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as TeamBioIndexImport } from './routes/team-bio/index'
import { Route as TeamBioIdImport } from './routes/team-bio/$id'
import { Route as AuthenticatedDashboardIndexImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardUserMessagesImport } from './routes/_authenticated/dashboard/userMessages'
import { Route as AuthenticatedDashboardUserCommentsImport } from './routes/_authenticated/dashboard/userComments'
import { Route as AuthenticatedDashboardTeamMembersImport } from './routes/_authenticated/dashboard/team-members'
import { Route as AuthenticatedDashboardHomePageCarouselImport } from './routes/_authenticated/dashboard/homePageCarousel'
import { Route as AuthenticatedDashboardFaqPageImport } from './routes/_authenticated/dashboard/faq-page'
import { Route as AuthenticatedDashboardCreatePartnerImport } from './routes/_authenticated/dashboard/createPartner'
import { Route as AuthenticatedDashboardClientsPageImport } from './routes/_authenticated/dashboard/clients-page'
import { Route as AuthenticatedDashboardBlogFormsImport } from './routes/_authenticated/dashboard/blogForms'
import { Route as AuthenticatedDashboardAdminSettingsImport } from './routes/_authenticated/dashboard/admin-settings'

// Create Virtual Routes

const WhatWeDoLazyImport = createFileRoute('/what-we-do')()
const OurExpertiseLazyImport = createFileRoute('/our-expertise')()
const OurClientsLazyImport = createFileRoute('/our-clients')()
const FaqPageLazyImport = createFileRoute('/faq-page')()

// Create/Update Routes

const WhatWeDoLazyRoute = WhatWeDoLazyImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/what-we-do.lazy').then((d) => d.Route))

const OurExpertiseLazyRoute = OurExpertiseLazyImport.update({
  id: '/our-expertise',
  path: '/our-expertise',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/our-expertise.lazy').then((d) => d.Route))

const OurClientsLazyRoute = OurClientsLazyImport.update({
  id: '/our-clients',
  path: '/our-clients',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/our-clients.lazy').then((d) => d.Route))

const FaqPageLazyRoute = FaqPageLazyImport.update({
  id: '/faq-page',
  path: '/faq-page',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/faq-page.lazy').then((d) => d.Route))

const OurTeamRoute = OurTeamImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRoute,
} as any)

const OurOfficesRoute = OurOfficesImport.update({
  id: '/our-offices',
  path: '/our-offices',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const ComingSoonRoute = ComingSoonImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AboutUsRoute = AboutUsImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRoute,
} as any)

const AboutMeRoute = AboutMeImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeamBioIndexRoute = TeamBioIndexImport.update({
  id: '/team-bio/',
  path: '/team-bio/',
  getParentRoute: () => rootRoute,
} as any)

const TeamBioIdRoute = TeamBioIdImport.update({
  id: '/team-bio/$id',
  path: '/team-bio/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardUserMessagesRoute =
  AuthenticatedDashboardUserMessagesImport.update({
    id: '/dashboard/userMessages',
    path: '/dashboard/userMessages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardUserCommentsRoute =
  AuthenticatedDashboardUserCommentsImport.update({
    id: '/dashboard/userComments',
    path: '/dashboard/userComments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardTeamMembersRoute =
  AuthenticatedDashboardTeamMembersImport.update({
    id: '/dashboard/team-members',
    path: '/dashboard/team-members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardHomePageCarouselRoute =
  AuthenticatedDashboardHomePageCarouselImport.update({
    id: '/dashboard/homePageCarousel',
    path: '/dashboard/homePageCarousel',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardFaqPageRoute =
  AuthenticatedDashboardFaqPageImport.update({
    id: '/dashboard/faq-page',
    path: '/dashboard/faq-page',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardCreatePartnerRoute =
  AuthenticatedDashboardCreatePartnerImport.update({
    id: '/dashboard/createPartner',
    path: '/dashboard/createPartner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClientsPageRoute =
  AuthenticatedDashboardClientsPageImport.update({
    id: '/dashboard/clients-page',
    path: '/dashboard/clients-page',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardBlogFormsRoute =
  AuthenticatedDashboardBlogFormsImport.update({
    id: '/dashboard/blogForms',
    path: '/dashboard/blogForms',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardAdminSettingsRoute =
  AuthenticatedDashboardAdminSettingsImport.update({
    id: '/dashboard/admin-settings',
    path: '/dashboard/admin-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeImport
      parentRoute: typeof rootRoute
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/our-offices': {
      id: '/our-offices'
      path: '/our-offices'
      fullPath: '/our-offices'
      preLoaderRoute: typeof OurOfficesImport
      parentRoute: typeof rootRoute
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamImport
      parentRoute: typeof rootRoute
    }
    '/faq-page': {
      id: '/faq-page'
      path: '/faq-page'
      fullPath: '/faq-page'
      preLoaderRoute: typeof FaqPageLazyImport
      parentRoute: typeof rootRoute
    }
    '/our-clients': {
      id: '/our-clients'
      path: '/our-clients'
      fullPath: '/our-clients'
      preLoaderRoute: typeof OurClientsLazyImport
      parentRoute: typeof rootRoute
    }
    '/our-expertise': {
      id: '/our-expertise'
      path: '/our-expertise'
      fullPath: '/our-expertise'
      preLoaderRoute: typeof OurExpertiseLazyImport
      parentRoute: typeof rootRoute
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoLazyImport
      parentRoute: typeof rootRoute
    }
    '/team-bio/$id': {
      id: '/team-bio/$id'
      path: '/team-bio/$id'
      fullPath: '/team-bio/$id'
      preLoaderRoute: typeof TeamBioIdImport
      parentRoute: typeof rootRoute
    }
    '/team-bio/': {
      id: '/team-bio/'
      path: '/team-bio'
      fullPath: '/team-bio'
      preLoaderRoute: typeof TeamBioIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard/admin-settings': {
      id: '/_authenticated/dashboard/admin-settings'
      path: '/dashboard/admin-settings'
      fullPath: '/dashboard/admin-settings'
      preLoaderRoute: typeof AuthenticatedDashboardAdminSettingsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/blogForms': {
      id: '/_authenticated/dashboard/blogForms'
      path: '/dashboard/blogForms'
      fullPath: '/dashboard/blogForms'
      preLoaderRoute: typeof AuthenticatedDashboardBlogFormsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/clients-page': {
      id: '/_authenticated/dashboard/clients-page'
      path: '/dashboard/clients-page'
      fullPath: '/dashboard/clients-page'
      preLoaderRoute: typeof AuthenticatedDashboardClientsPageImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/createPartner': {
      id: '/_authenticated/dashboard/createPartner'
      path: '/dashboard/createPartner'
      fullPath: '/dashboard/createPartner'
      preLoaderRoute: typeof AuthenticatedDashboardCreatePartnerImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/faq-page': {
      id: '/_authenticated/dashboard/faq-page'
      path: '/dashboard/faq-page'
      fullPath: '/dashboard/faq-page'
      preLoaderRoute: typeof AuthenticatedDashboardFaqPageImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/homePageCarousel': {
      id: '/_authenticated/dashboard/homePageCarousel'
      path: '/dashboard/homePageCarousel'
      fullPath: '/dashboard/homePageCarousel'
      preLoaderRoute: typeof AuthenticatedDashboardHomePageCarouselImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/team-members': {
      id: '/_authenticated/dashboard/team-members'
      path: '/dashboard/team-members'
      fullPath: '/dashboard/team-members'
      preLoaderRoute: typeof AuthenticatedDashboardTeamMembersImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/userComments': {
      id: '/_authenticated/dashboard/userComments'
      path: '/dashboard/userComments'
      fullPath: '/dashboard/userComments'
      preLoaderRoute: typeof AuthenticatedDashboardUserCommentsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/userMessages': {
      id: '/_authenticated/dashboard/userMessages'
      path: '/dashboard/userMessages'
      fullPath: '/dashboard/userMessages'
      preLoaderRoute: typeof AuthenticatedDashboardUserMessagesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardAdminSettingsRoute: typeof AuthenticatedDashboardAdminSettingsRoute
  AuthenticatedDashboardBlogFormsRoute: typeof AuthenticatedDashboardBlogFormsRoute
  AuthenticatedDashboardClientsPageRoute: typeof AuthenticatedDashboardClientsPageRoute
  AuthenticatedDashboardCreatePartnerRoute: typeof AuthenticatedDashboardCreatePartnerRoute
  AuthenticatedDashboardFaqPageRoute: typeof AuthenticatedDashboardFaqPageRoute
  AuthenticatedDashboardHomePageCarouselRoute: typeof AuthenticatedDashboardHomePageCarouselRoute
  AuthenticatedDashboardTeamMembersRoute: typeof AuthenticatedDashboardTeamMembersRoute
  AuthenticatedDashboardUserCommentsRoute: typeof AuthenticatedDashboardUserCommentsRoute
  AuthenticatedDashboardUserMessagesRoute: typeof AuthenticatedDashboardUserMessagesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardAdminSettingsRoute:
    AuthenticatedDashboardAdminSettingsRoute,
  AuthenticatedDashboardBlogFormsRoute: AuthenticatedDashboardBlogFormsRoute,
  AuthenticatedDashboardClientsPageRoute:
    AuthenticatedDashboardClientsPageRoute,
  AuthenticatedDashboardCreatePartnerRoute:
    AuthenticatedDashboardCreatePartnerRoute,
  AuthenticatedDashboardFaqPageRoute: AuthenticatedDashboardFaqPageRoute,
  AuthenticatedDashboardHomePageCarouselRoute:
    AuthenticatedDashboardHomePageCarouselRoute,
  AuthenticatedDashboardTeamMembersRoute:
    AuthenticatedDashboardTeamMembersRoute,
  AuthenticatedDashboardUserCommentsRoute:
    AuthenticatedDashboardUserCommentsRoute,
  AuthenticatedDashboardUserMessagesRoute:
    AuthenticatedDashboardUserMessagesRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about-me': typeof AboutMeRoute
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/our-offices': typeof OurOfficesRoute
  '/our-team': typeof OurTeamRoute
  '/faq-page': typeof FaqPageLazyRoute
  '/our-clients': typeof OurClientsLazyRoute
  '/our-expertise': typeof OurExpertiseLazyRoute
  '/what-we-do': typeof WhatWeDoLazyRoute
  '/team-bio/$id': typeof TeamBioIdRoute
  '/team-bio': typeof TeamBioIndexRoute
  '/dashboard/admin-settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/dashboard/blogForms': typeof AuthenticatedDashboardBlogFormsRoute
  '/dashboard/clients-page': typeof AuthenticatedDashboardClientsPageRoute
  '/dashboard/createPartner': typeof AuthenticatedDashboardCreatePartnerRoute
  '/dashboard/faq-page': typeof AuthenticatedDashboardFaqPageRoute
  '/dashboard/homePageCarousel': typeof AuthenticatedDashboardHomePageCarouselRoute
  '/dashboard/team-members': typeof AuthenticatedDashboardTeamMembersRoute
  '/dashboard/userComments': typeof AuthenticatedDashboardUserCommentsRoute
  '/dashboard/userMessages': typeof AuthenticatedDashboardUserMessagesRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about-me': typeof AboutMeRoute
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/our-offices': typeof OurOfficesRoute
  '/our-team': typeof OurTeamRoute
  '/faq-page': typeof FaqPageLazyRoute
  '/our-clients': typeof OurClientsLazyRoute
  '/our-expertise': typeof OurExpertiseLazyRoute
  '/what-we-do': typeof WhatWeDoLazyRoute
  '/team-bio/$id': typeof TeamBioIdRoute
  '/team-bio': typeof TeamBioIndexRoute
  '/dashboard/admin-settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/dashboard/blogForms': typeof AuthenticatedDashboardBlogFormsRoute
  '/dashboard/clients-page': typeof AuthenticatedDashboardClientsPageRoute
  '/dashboard/createPartner': typeof AuthenticatedDashboardCreatePartnerRoute
  '/dashboard/faq-page': typeof AuthenticatedDashboardFaqPageRoute
  '/dashboard/homePageCarousel': typeof AuthenticatedDashboardHomePageCarouselRoute
  '/dashboard/team-members': typeof AuthenticatedDashboardTeamMembersRoute
  '/dashboard/userComments': typeof AuthenticatedDashboardUserCommentsRoute
  '/dashboard/userMessages': typeof AuthenticatedDashboardUserMessagesRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about-me': typeof AboutMeRoute
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/our-offices': typeof OurOfficesRoute
  '/our-team': typeof OurTeamRoute
  '/faq-page': typeof FaqPageLazyRoute
  '/our-clients': typeof OurClientsLazyRoute
  '/our-expertise': typeof OurExpertiseLazyRoute
  '/what-we-do': typeof WhatWeDoLazyRoute
  '/team-bio/$id': typeof TeamBioIdRoute
  '/team-bio/': typeof TeamBioIndexRoute
  '/_authenticated/dashboard/admin-settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/_authenticated/dashboard/blogForms': typeof AuthenticatedDashboardBlogFormsRoute
  '/_authenticated/dashboard/clients-page': typeof AuthenticatedDashboardClientsPageRoute
  '/_authenticated/dashboard/createPartner': typeof AuthenticatedDashboardCreatePartnerRoute
  '/_authenticated/dashboard/faq-page': typeof AuthenticatedDashboardFaqPageRoute
  '/_authenticated/dashboard/homePageCarousel': typeof AuthenticatedDashboardHomePageCarouselRoute
  '/_authenticated/dashboard/team-members': typeof AuthenticatedDashboardTeamMembersRoute
  '/_authenticated/dashboard/userComments': typeof AuthenticatedDashboardUserCommentsRoute
  '/_authenticated/dashboard/userMessages': typeof AuthenticatedDashboardUserMessagesRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about-me'
    | '/about-us'
    | '/auth'
    | '/coming-soon'
    | '/contact'
    | '/our-offices'
    | '/our-team'
    | '/faq-page'
    | '/our-clients'
    | '/our-expertise'
    | '/what-we-do'
    | '/team-bio/$id'
    | '/team-bio'
    | '/dashboard/admin-settings'
    | '/dashboard/blogForms'
    | '/dashboard/clients-page'
    | '/dashboard/createPartner'
    | '/dashboard/faq-page'
    | '/dashboard/homePageCarousel'
    | '/dashboard/team-members'
    | '/dashboard/userComments'
    | '/dashboard/userMessages'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about-me'
    | '/about-us'
    | '/auth'
    | '/coming-soon'
    | '/contact'
    | '/our-offices'
    | '/our-team'
    | '/faq-page'
    | '/our-clients'
    | '/our-expertise'
    | '/what-we-do'
    | '/team-bio/$id'
    | '/team-bio'
    | '/dashboard/admin-settings'
    | '/dashboard/blogForms'
    | '/dashboard/clients-page'
    | '/dashboard/createPartner'
    | '/dashboard/faq-page'
    | '/dashboard/homePageCarousel'
    | '/dashboard/team-members'
    | '/dashboard/userComments'
    | '/dashboard/userMessages'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-me'
    | '/about-us'
    | '/auth'
    | '/coming-soon'
    | '/contact'
    | '/our-offices'
    | '/our-team'
    | '/faq-page'
    | '/our-clients'
    | '/our-expertise'
    | '/what-we-do'
    | '/team-bio/$id'
    | '/team-bio/'
    | '/_authenticated/dashboard/admin-settings'
    | '/_authenticated/dashboard/blogForms'
    | '/_authenticated/dashboard/clients-page'
    | '/_authenticated/dashboard/createPartner'
    | '/_authenticated/dashboard/faq-page'
    | '/_authenticated/dashboard/homePageCarousel'
    | '/_authenticated/dashboard/team-members'
    | '/_authenticated/dashboard/userComments'
    | '/_authenticated/dashboard/userMessages'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutMeRoute: typeof AboutMeRoute
  AboutUsRoute: typeof AboutUsRoute
  AuthRoute: typeof AuthRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ContactRoute: typeof ContactRoute
  OurOfficesRoute: typeof OurOfficesRoute
  OurTeamRoute: typeof OurTeamRoute
  FaqPageLazyRoute: typeof FaqPageLazyRoute
  OurClientsLazyRoute: typeof OurClientsLazyRoute
  OurExpertiseLazyRoute: typeof OurExpertiseLazyRoute
  WhatWeDoLazyRoute: typeof WhatWeDoLazyRoute
  TeamBioIdRoute: typeof TeamBioIdRoute
  TeamBioIndexRoute: typeof TeamBioIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutMeRoute: AboutMeRoute,
  AboutUsRoute: AboutUsRoute,
  AuthRoute: AuthRoute,
  ComingSoonRoute: ComingSoonRoute,
  ContactRoute: ContactRoute,
  OurOfficesRoute: OurOfficesRoute,
  OurTeamRoute: OurTeamRoute,
  FaqPageLazyRoute: FaqPageLazyRoute,
  OurClientsLazyRoute: OurClientsLazyRoute,
  OurExpertiseLazyRoute: OurExpertiseLazyRoute,
  WhatWeDoLazyRoute: WhatWeDoLazyRoute,
  TeamBioIdRoute: TeamBioIdRoute,
  TeamBioIndexRoute: TeamBioIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/about-me",
        "/about-us",
        "/auth",
        "/coming-soon",
        "/contact",
        "/our-offices",
        "/our-team",
        "/faq-page",
        "/our-clients",
        "/our-expertise",
        "/what-we-do",
        "/team-bio/$id",
        "/team-bio/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/dashboard/admin-settings",
        "/_authenticated/dashboard/blogForms",
        "/_authenticated/dashboard/clients-page",
        "/_authenticated/dashboard/createPartner",
        "/_authenticated/dashboard/faq-page",
        "/_authenticated/dashboard/homePageCarousel",
        "/_authenticated/dashboard/team-members",
        "/_authenticated/dashboard/userComments",
        "/_authenticated/dashboard/userMessages",
        "/_authenticated/dashboard/"
      ]
    },
    "/about-me": {
      "filePath": "about-me.tsx"
    },
    "/about-us": {
      "filePath": "about-us.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/coming-soon": {
      "filePath": "coming-soon.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/our-offices": {
      "filePath": "our-offices.tsx"
    },
    "/our-team": {
      "filePath": "our-team.tsx"
    },
    "/faq-page": {
      "filePath": "faq-page.lazy.jsx"
    },
    "/our-clients": {
      "filePath": "our-clients.lazy.tsx"
    },
    "/our-expertise": {
      "filePath": "our-expertise.lazy.tsx"
    },
    "/what-we-do": {
      "filePath": "what-we-do.lazy.tsx"
    },
    "/team-bio/$id": {
      "filePath": "team-bio/$id.tsx"
    },
    "/team-bio/": {
      "filePath": "team-bio/index.tsx"
    },
    "/_authenticated/dashboard/admin-settings": {
      "filePath": "_authenticated/dashboard/admin-settings.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/blogForms": {
      "filePath": "_authenticated/dashboard/blogForms.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clients-page": {
      "filePath": "_authenticated/dashboard/clients-page.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/createPartner": {
      "filePath": "_authenticated/dashboard/createPartner.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/faq-page": {
      "filePath": "_authenticated/dashboard/faq-page.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/homePageCarousel": {
      "filePath": "_authenticated/dashboard/homePageCarousel.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/team-members": {
      "filePath": "_authenticated/dashboard/team-members.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/userComments": {
      "filePath": "_authenticated/dashboard/userComments.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/userMessages": {
      "filePath": "_authenticated/dashboard/userMessages.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/": {
      "filePath": "_authenticated/dashboard/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
