/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OurTeamImport } from './routes/our-team'
import { Route as OurOfficesImport } from './routes/our-offices'
import { Route as ContactImport } from './routes/contact'
import { Route as ComingSoonImport } from './routes/coming-soon'
import { Route as AuthImport } from './routes/auth'
import { Route as AdminSettingsImport } from './routes/admin-settings'
import { Route as AboutUsImport } from './routes/about-us'
import { Route as AboutMeImport } from './routes/about-me'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as TeamBioIndexImport } from './routes/team-bio/index'
import { Route as TeamBioIdImport } from './routes/team-bio/$id'
import { Route as AuthenticatedMessageImport } from './routes/_authenticated/message'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommentsImport } from './routes/_authenticated/comments'

// Create Virtual Routes

const WhatWeDoLazyImport = createFileRoute('/what-we-do')()
const OurExpertiseLazyImport = createFileRoute('/our-expertise')()
const OurClientsLazyImport = createFileRoute('/our-clients')()
const FaqPageLazyImport = createFileRoute('/faq-page')()

// Create/Update Routes

const WhatWeDoLazyRoute = WhatWeDoLazyImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/what-we-do.lazy').then((d) => d.Route))

const OurExpertiseLazyRoute = OurExpertiseLazyImport.update({
  id: '/our-expertise',
  path: '/our-expertise',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/our-expertise.lazy').then((d) => d.Route))

const OurClientsLazyRoute = OurClientsLazyImport.update({
  id: '/our-clients',
  path: '/our-clients',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/our-clients.lazy').then((d) => d.Route))

const FaqPageLazyRoute = FaqPageLazyImport.update({
  id: '/faq-page',
  path: '/faq-page',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/faq-page.lazy').then((d) => d.Route))

const OurTeamRoute = OurTeamImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRoute,
} as any)

const OurOfficesRoute = OurOfficesImport.update({
  id: '/our-offices',
  path: '/our-offices',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const ComingSoonRoute = ComingSoonImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AdminSettingsRoute = AdminSettingsImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => rootRoute,
} as any)

const AboutUsRoute = AboutUsImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRoute,
} as any)

const AboutMeRoute = AboutMeImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeamBioIndexRoute = TeamBioIndexImport.update({
  id: '/team-bio/',
  path: '/team-bio/',
  getParentRoute: () => rootRoute,
} as any)

const TeamBioIdRoute = TeamBioIdImport.update({
  id: '/team-bio/$id',
  path: '/team-bio/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedMessageRoute = AuthenticatedMessageImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCommentsRoute = AuthenticatedCommentsImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeImport
      parentRoute: typeof rootRoute
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsImport
      parentRoute: typeof rootRoute
    }
    '/admin-settings': {
      id: '/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AdminSettingsImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/our-offices': {
      id: '/our-offices'
      path: '/our-offices'
      fullPath: '/our-offices'
      preLoaderRoute: typeof OurOfficesImport
      parentRoute: typeof rootRoute
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamImport
      parentRoute: typeof rootRoute
    }
    '/faq-page': {
      id: '/faq-page'
      path: '/faq-page'
      fullPath: '/faq-page'
      preLoaderRoute: typeof FaqPageLazyImport
      parentRoute: typeof rootRoute
    }
    '/our-clients': {
      id: '/our-clients'
      path: '/our-clients'
      fullPath: '/our-clients'
      preLoaderRoute: typeof OurClientsLazyImport
      parentRoute: typeof rootRoute
    }
    '/our-expertise': {
      id: '/our-expertise'
      path: '/our-expertise'
      fullPath: '/our-expertise'
      preLoaderRoute: typeof OurExpertiseLazyImport
      parentRoute: typeof rootRoute
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/comments': {
      id: '/_authenticated/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof AuthenticatedCommentsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/message': {
      id: '/_authenticated/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof AuthenticatedMessageImport
      parentRoute: typeof AuthenticatedImport
    }
    '/team-bio/$id': {
      id: '/team-bio/$id'
      path: '/team-bio/$id'
      fullPath: '/team-bio/$id'
      preLoaderRoute: typeof TeamBioIdImport
      parentRoute: typeof rootRoute
    }
    '/team-bio/': {
      id: '/team-bio/'
      path: '/team-bio'
      fullPath: '/team-bio'
      preLoaderRoute: typeof TeamBioIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedCommentsRoute: typeof AuthenticatedCommentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMessageRoute: typeof AuthenticatedMessageRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCommentsRoute: AuthenticatedCommentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMessageRoute: AuthenticatedMessageRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about-me': typeof AboutMeRoute
  '/about-us': typeof AboutUsRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/our-offices': typeof OurOfficesRoute
  '/our-team': typeof OurTeamRoute
  '/faq-page': typeof FaqPageLazyRoute
  '/our-clients': typeof OurClientsLazyRoute
  '/our-expertise': typeof OurExpertiseLazyRoute
  '/what-we-do': typeof WhatWeDoLazyRoute
  '/comments': typeof AuthenticatedCommentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/message': typeof AuthenticatedMessageRoute
  '/team-bio/$id': typeof TeamBioIdRoute
  '/team-bio': typeof TeamBioIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about-me': typeof AboutMeRoute
  '/about-us': typeof AboutUsRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/our-offices': typeof OurOfficesRoute
  '/our-team': typeof OurTeamRoute
  '/faq-page': typeof FaqPageLazyRoute
  '/our-clients': typeof OurClientsLazyRoute
  '/our-expertise': typeof OurExpertiseLazyRoute
  '/what-we-do': typeof WhatWeDoLazyRoute
  '/comments': typeof AuthenticatedCommentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/message': typeof AuthenticatedMessageRoute
  '/team-bio/$id': typeof TeamBioIdRoute
  '/team-bio': typeof TeamBioIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about-me': typeof AboutMeRoute
  '/about-us': typeof AboutUsRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/auth': typeof AuthRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/our-offices': typeof OurOfficesRoute
  '/our-team': typeof OurTeamRoute
  '/faq-page': typeof FaqPageLazyRoute
  '/our-clients': typeof OurClientsLazyRoute
  '/our-expertise': typeof OurExpertiseLazyRoute
  '/what-we-do': typeof WhatWeDoLazyRoute
  '/_authenticated/comments': typeof AuthenticatedCommentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/message': typeof AuthenticatedMessageRoute
  '/team-bio/$id': typeof TeamBioIdRoute
  '/team-bio/': typeof TeamBioIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about-me'
    | '/about-us'
    | '/admin-settings'
    | '/auth'
    | '/coming-soon'
    | '/contact'
    | '/our-offices'
    | '/our-team'
    | '/faq-page'
    | '/our-clients'
    | '/our-expertise'
    | '/what-we-do'
    | '/comments'
    | '/dashboard'
    | '/message'
    | '/team-bio/$id'
    | '/team-bio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about-me'
    | '/about-us'
    | '/admin-settings'
    | '/auth'
    | '/coming-soon'
    | '/contact'
    | '/our-offices'
    | '/our-team'
    | '/faq-page'
    | '/our-clients'
    | '/our-expertise'
    | '/what-we-do'
    | '/comments'
    | '/dashboard'
    | '/message'
    | '/team-bio/$id'
    | '/team-bio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-me'
    | '/about-us'
    | '/admin-settings'
    | '/auth'
    | '/coming-soon'
    | '/contact'
    | '/our-offices'
    | '/our-team'
    | '/faq-page'
    | '/our-clients'
    | '/our-expertise'
    | '/what-we-do'
    | '/_authenticated/comments'
    | '/_authenticated/dashboard'
    | '/_authenticated/message'
    | '/team-bio/$id'
    | '/team-bio/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutMeRoute: typeof AboutMeRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AuthRoute: typeof AuthRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ContactRoute: typeof ContactRoute
  OurOfficesRoute: typeof OurOfficesRoute
  OurTeamRoute: typeof OurTeamRoute
  FaqPageLazyRoute: typeof FaqPageLazyRoute
  OurClientsLazyRoute: typeof OurClientsLazyRoute
  OurExpertiseLazyRoute: typeof OurExpertiseLazyRoute
  WhatWeDoLazyRoute: typeof WhatWeDoLazyRoute
  TeamBioIdRoute: typeof TeamBioIdRoute
  TeamBioIndexRoute: typeof TeamBioIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutMeRoute: AboutMeRoute,
  AboutUsRoute: AboutUsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AuthRoute: AuthRoute,
  ComingSoonRoute: ComingSoonRoute,
  ContactRoute: ContactRoute,
  OurOfficesRoute: OurOfficesRoute,
  OurTeamRoute: OurTeamRoute,
  FaqPageLazyRoute: FaqPageLazyRoute,
  OurClientsLazyRoute: OurClientsLazyRoute,
  OurExpertiseLazyRoute: OurExpertiseLazyRoute,
  WhatWeDoLazyRoute: WhatWeDoLazyRoute,
  TeamBioIdRoute: TeamBioIdRoute,
  TeamBioIndexRoute: TeamBioIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/about-me",
        "/about-us",
        "/admin-settings",
        "/auth",
        "/coming-soon",
        "/contact",
        "/our-offices",
        "/our-team",
        "/faq-page",
        "/our-clients",
        "/our-expertise",
        "/what-we-do",
        "/team-bio/$id",
        "/team-bio/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/comments",
        "/_authenticated/dashboard",
        "/_authenticated/message"
      ]
    },
    "/about-me": {
      "filePath": "about-me.tsx"
    },
    "/about-us": {
      "filePath": "about-us.tsx"
    },
    "/admin-settings": {
      "filePath": "admin-settings.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/coming-soon": {
      "filePath": "coming-soon.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/our-offices": {
      "filePath": "our-offices.tsx"
    },
    "/our-team": {
      "filePath": "our-team.tsx"
    },
    "/faq-page": {
      "filePath": "faq-page.lazy.jsx"
    },
    "/our-clients": {
      "filePath": "our-clients.lazy.tsx"
    },
    "/our-expertise": {
      "filePath": "our-expertise.lazy.tsx"
    },
    "/what-we-do": {
      "filePath": "what-we-do.lazy.tsx"
    },
    "/_authenticated/comments": {
      "filePath": "_authenticated/comments.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/message": {
      "filePath": "_authenticated/message.tsx",
      "parent": "/_authenticated"
    },
    "/team-bio/$id": {
      "filePath": "team-bio/$id.tsx"
    },
    "/team-bio/": {
      "filePath": "team-bio/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
